#!/bin/bash

# Script to create GitHub issues for HIGH/CRITICAL vulnerabilities from audit results
# This can be run manually or integrated into CI/CD

set -e

BRANCH="${1:-v5-stable}"
REPO_OWNER="${GITHUB_REPOSITORY_OWNER:-aws-amplify}"
REPO_NAME="${GITHUB_REPOSITORY_NAME:-amplify-js}"

echo "🔍 Checking for HIGH/CRITICAL vulnerabilities in $BRANCH..."

# Run audit and capture JSON output
AUDIT_OUTPUT=$(yarn audit --json 2>/dev/null || true)

# Parse HIGH and CRITICAL vulnerabilities
CRITICAL_VULNS=$(echo "$AUDIT_OUTPUT" | jq -r 'select(.type=="auditAdvisory") | select(.data.advisory.severity=="critical" or .data.advisory.severity=="high") | .data.advisory' 2>/dev/null || echo "[]")

if [ -z "$CRITICAL_VULNS" ] || [ "$CRITICAL_VULNS" = "[]" ]; then
    echo "✅ No HIGH or CRITICAL vulnerabilities found"
    exit 0
fi

echo "⚠️  Found HIGH/CRITICAL vulnerabilities. Generating issue report..."

# Create issue body
cat > /tmp/security-issue.md << EOF
## 🚨 Security Vulnerabilities Detected in $BRANCH

This issue was automatically created by the LTS Security Monitor.

**Branch:** \`$BRANCH\`
**Scan Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

### Vulnerabilities Found

EOF

# Parse each vulnerability and add to issue
echo "$AUDIT_OUTPUT" | jq -r '
  select(.type=="auditAdvisory") | 
  select(.data.advisory.severity=="critical" or .data.advisory.severity=="high") |
  .data.advisory |
  "#### [\(.severity | ascii_upcase)] \(.title)\n\n" +
  "- **Package:** `\(.module_name)`\n" +
  "- **Vulnerable Versions:** \(.vulnerable_versions)\n" +
  "- **Patched Versions:** \(.patched_versions)\n" +
  "- **CVE:** \(.cves | join(", "))\n" +
  "- **Advisory:** \(.url)\n\n" +
  "**Overview:**\n\(.overview)\n\n" +
  "**Recommendation:**\n\(.recommendation)\n\n" +
  "---\n"
' >> /tmp/security-issue.md 2>/dev/null || true

cat >> /tmp/security-issue.md << EOF

### Action Required

Please review these vulnerabilities and:
1. Assess impact on the $BRANCH branch
2. Determine if patches can be safely backported
3. Update dependencies or document mitigation strategy
4. Close this issue once addressed

### Related Links

- [Security Policy](https://github.com/$REPO_OWNER/$REPO_NAME/security/policy)
- [Code Scanning Results](https://github.com/$REPO_OWNER/$REPO_NAME/security/code-scanning?query=is:open+branch:$BRANCH)

---
*This issue was automatically generated by the LTS Security Monitoring system.*
EOF

echo ""
echo "📋 Issue content generated:"
echo "---"
cat /tmp/security-issue.md
echo "---"
echo ""

# If running in GitHub Actions with token, create the issue
if [ -n "$GITHUB_TOKEN" ]; then
    echo "🔧 Creating GitHub issue..."
    
    ISSUE_TITLE="[Security] HIGH/CRITICAL vulnerabilities in $BRANCH ($(date +%Y-%m-%d))"
    
    gh issue create \
        --title "$ISSUE_TITLE" \
        --body-file /tmp/security-issue.md \
        --label "security,dependencies,$BRANCH" \
        --repo "$REPO_OWNER/$REPO_NAME" || {
        echo "⚠️  Failed to create issue. Make sure GITHUB_TOKEN is set with appropriate permissions."
        exit 1
    }
    
    echo "✅ Issue created successfully"
else
    echo "ℹ️  To create a GitHub issue, set GITHUB_TOKEN and run:"
    echo "   export GITHUB_TOKEN=your_token"
    echo "   ./scripts/security-audit/create-security-issues.sh $BRANCH"
fi

# Cleanup
rm -f /tmp/security-issue.md
