# Dependabot CLI job definition for security updates.
# Using `update-type: security` restricts the CLI to only propose updates
# that resolve known vulnerabilities from the GitHub Advisory Database.
#
# Docs: https://github.com/dependabot/cli

job:
  package-manager: npm_and_yarn
  allowed-updates:
    - update-type: security
  source:
    provider: github
    repo: aws-amplify/amplify-js
    directory: /
credentials:
  - type: git_source
    host: github.com
    username: x-access-token
    password: $LOCAL_GITHUB_ACCESS_TOKEN
